### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by devalexandre** [ketgo/nameko-mongoengine#1]
config.yml
![image](https://user-images.githubusercontent.com/4489558/156957798-07203733-015e-4464-a8f5-0535e336dd1a.png)

![image](https://user-images.githubusercontent.com/4489558/156957587-0acd1d34-e73c-4032-a417-98f68bc234a0.png)

**Comment by ketgo** [comment]
Hi @devalexandre 

I think you are seeing this error because you have not specified the config file in the `nameko run` command. I have just pushed a complete [example](https://github.com/ketgo/nameko-mongoengine/tree/master/example) in the repo for reference.
